config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"

  # Reveal health status
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path
  root "authors#index"

  # Authors routes with fetch_latest
  resources :authors do
    member do
      get :fetch_latest
      get :fetch_latest_spotify
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy fetch_latest fetch_latest_spotify ]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @author.destroy!
    respond_to do |format|
      format.html { redirect_to authors_path, notice: "Author was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end


  def fetch_latest
    youtube = YoutubeService.new("AIzaSyDZHUNXbzEm7gmIo5tZ5ueF0bp7Arwx9JQ")
    url = @author.link
    channel_id = youtube.resolve_channel_id_from_url(url)

    if channel_id.nil?
      @videos = []
      flash[:alert] = "Could not find YouTube channel for link: #{url}"
      return
    end

    response = youtube.latest_videos(channel_id, 5)
    @videos = if response&.items&.any?
                response.items.map do |item|
                  {
                    title: item.snippet.title,
                    link: "https://www.youtube.com/watch?v=#{item.id.video_id}",
                    img: item.snippet.thumbnails.medium.url,
                    release_date: item.snippet.published_at
                  }
                end
              else
                []
              end
  end


  def fetch_latest_spotify
    client_id = "ae1560f96c754a0bb73b7d8bc27f3f0f"
    client_secret = "a3214242872e4d43b53c58ce766e4e04"
    spotify = SpotifyService.new(client_id, client_secret)

    url = @author.img

    if url.include?("/artist/")
      id = spotify.resolve_artist_id_from_url(url)
      if id.nil?
        @items = []
        flash[:alert] = "Could not find artist for link: #{url}"
        return
      end
      @items = spotify.latest_albums(id, 5)
    elsif url.include?("/show/")
      id = spotify.resolve_show_id_from_url(url)
      if id.nil?
        @items = []
        flash[:alert] = "Could not find podcast for link: #{url}"
        return
      end
      @items = spotify.latest_episodes(id, 5)
    else
      @items = []
      flash[:alert] = "Invalid Spotify link: #{url}"
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :link, :img)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= author.link %>
  </p>

  <p>
    <strong>Img:</strong>
    <%= author.img %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<% content_for :title, "Editing author" %>

<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/fetch_latest.html.erb
<h1>Latest videos</h1>

<% if @videos.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Thumbnail</th>
    </tr>
    </thead>
    <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video[:title] %></td>
        <td><%= link_to "Open", video[:link], target: "_blank" %></td>
        <td><img src="<%= video[:img] %>" width="120"></td>
        <td>Release date: <%= video[:release_date] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Failed to load videos.</p>
<% end %>

app/views/authors/fetch_latest_spotify.html.erb
<h1>Latest Spotify Items</h1>

<% if @items.any? %>
  <ul>
    <% @items.each do |item| %>
      <li>
        <h3><%= item[:title] %></h3>
        <p>Release date: <%= item[:release_date] %></p>
        <% if item[:img] %>
          <img src="<%= item[:img] %>" alt="<%= item[:title] %>" width="200">
        <% end %>
        <p><%= link_to "Listen on Spotify", item[:link], target: "_blank" %></p>
      </li>
      <hr>
    <% end %>
  </ul>
<% else %>
  <p>Could not fetch items.</p>
<% end %>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Authors" %>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
    <p>
      <%= link_to "Show latest Youtube videos", fetch_latest_author_path(author), class: "btn btn-primary" %>
    </p>
    <p>
      <%= link_to "Fetch latest Spotify uploads", fetch_latest_spotify_author_path(author), class: "btn btn-success" %>
    </p>
  <% end %>
</div>
<hr>
<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<% content_for :title, "New author" %>

<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Helloworld" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello World</h1>